### PR TITLE
Todo-List

### PR DESCRIPTION
**Pull request by Naqhid**
TODO List are the lists that we generally use to maintain our day to day tasks or list of everything that we have to do, with the most important tasks at the top of the list, and the least important tasks at the bottom. It is helpful in planning our daily schedules. We can add more tasks any time and delete a task which is completed. The four major tasks that we can perform in a TODO list are:

Add tasks
Update tasks
Read tasks
Delete tasks

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes.
### Changes to make 🙅🏿 🙅🏿 🙅🏿 
- Fix linter errors
- Do not create a new PR for every submission. You are required to use only one PR for the entire cycle of reviews. This will help the TSE to see previous changes requested. Please make the requested changes in PR 3 (you will need to re-open it) and re-submit for another review. This means PR 4 (current) must be closed.


### Martin Afani
#### Slack: whiz25

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**. 

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED
>Before we dive into the project specifics, make sure that you have a professional repo.
- [ ] Add a PR message with a brief description of the implemented features.
- [ ] Always ensure to follow Github flow appropriately. Your feature branch should be compared to the development branch, and not the other way round.
- [ ] Always use a single PR for all reviews for a project unless it's stated in the project description and has a number of milestones. 
- [ ] You have failing linters detected. Give them a fix a submit entirely.

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Naqhid  :handshake: :handshake: :handshake: 
> # STATUS: CHANGES REQUIRED  
> ## Hey Happy Coder, 👋🏽
> **This is a great project you have going on, well-done lad and thanks for implementing the changes requested earlier on**.
> 
> **However, there are a few sections to improve before your project is approved.** 
> 
> ### REQUIRED
> > Before we dive into the project specifics, make sure that you have a professional repo.
> 
> * [ ]  Add a PR message with a brief description of the implemented features.
> * [ ]  Always ensure to follow Github flow appropriately. Your feature branch should be compared to the development branch, and not the other way round.
> * [ ]  Always use a single PR for all reviews for a project unless it's stated in the project description and has a number of milestones.
> * [ ]  You have failing linters detected. Give them a fix a submit entirely.
> 
> ### Kindly make all the requested changes and submit another CRR. 
> **Cheers tropical_drink and Happy coding computer**
> 
> Mention @mke2111 in this thread and I'll be glad to help. 
> 
> ### Best regards
> Slack  Roy Mukuye
> Twitter  [Roy Mukuye](https://twitter.com/Roymkenya)
> LinkedIn  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)


@Naqhid , the previous review requested changes should be addressed 100% before requesting an other review, kindly, address all of the issues as suggested by the previous reviewer
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please ensure all linting issues are checked and fixed.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello, there @Naqhid 👋🏾 great effort in this milestone 😄 However you have not worked on the last TSE's comments regarding linters. To check for eslint errors run `npx eslint . ` on your terminal and you will see a list of errors. Most of them can be easily fixed if you just run `npx eslint . --fix` and the rest will have to be manually fixed. Kindly work on this. Refer to [microverse linters](https://github.com/microverseinc/linters-config/tree/master/javascript) if you need further information

That's all, Kindly submit another review when done 😄 

If you have any questions tag my name (@mimipeshy) in the comment section and I will be glad to help.

Regards,
Peris Ndanu

**Review by afanimartin — APPROVED** [review]
## Approved ✅ ✅ ✅ 
Nice work making the requested change. Merge and proceed to the next project.

### Martin
#### Slack: whiz25

**Pull request merged**
